[build]
  publish = "public"
  functions = "netlify/functions"
  command = "# no build command needed"

[functions]
  node_bundler = "esbuild"

# Redirect all API calls to our serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 